export const SET_KAIJU_DNA = "SET_KAIJU_DNA";
export const SET_KAIJU_DNA_ERROR = "SET_KAIJU_DNA_ERROR";
export const GET_KAIJUS_REQUESTED = "GET_KAIJUS_REQUESTED";
export const GET_KAIJUS_SUCCESS = "GET_KAIJUS_SUCCESS";
export const GET_KAIJUS_ERROR = "GET_KAIJUS_ERROR";
export const CREATE_KAIJU_ERROR = "CREATE_KAIJU_ERROR";
